#!/usr/bin/env python3
"""
Single-test framework for chart-to-code -> evaluation -> controlled style edits.

Pipeline:
1) Read reference image size and compute integer figsize.
2) Call model for matplotlib code generation from image.
3) Execute generated code, save rendered image into temp_image/.
4) Call model to score rendered image against reference image.
5) Call model to propose editable code-line replacements (return_checklist).
6) Apply replacements and render modified image into modified_image/.
"""

from __future__ import annotations

import argparse
import base64
import concurrent.futures
import hashlib
import json
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, List, Tuple

from openai import OpenAI
from PIL import Image

DEFAULT_API_KEY = os.getenv("OPENAI_API_KEY", "sk-mYDVzMMHpaUyuSWqwi42JaUs1ZNCBKaYxQuTHNX1siu2wEVG")
DEFAULT_BASE_URL = os.getenv("OPENAI_BASE_URL", "http://35.220.164.252:3888/v1")
DEFAULT_MODEL = os.getenv("OPENAI_MODEL", "gpt-5.2")
TIMEOUT = 180
MAX_TOKENS = 4096
TEMPERATURE = 0.0

QUERY = (
    "The graph below shows the titration curve that results when 100. mL of 0.0250 M acetic acid is "
    "titrated with 0.100 M $NaOH$. <image 1> Which of the following indicators is the best choice for "
    "this titration?\nA. Methyl orange, whose pH range of color change is 3.2 - 4.4 .\nB. Methyl red, "
    "whose pH range of color change is 4.8 - 6.0 .\nC. MBromothymol blue, whose pH range of color change "
    "is 6.1 - 7.6 .\nD. Phenolphthalein, whose pH range of color change is 8.2 - 10.0 .\nE. Alizarin, "
    "whose pH range of color change is 11.0 - 12.4 ."
)
TARGET = "D"
DEFAULT_IMAGE_PATH = "/mnt/shared-storage-user/zhengyuting/SIP/original_image/MMMU-Chemistry/7.png"
DEFAULT_QA_ROOT = Path("/mnt/shared-storage-user/zhengyuting/SIP_exp/original_data")
DEFAULT_IMAGE_ROOT = Path("/mnt/shared-storage-user/zhengyuting/SIP_exp/modified_image")
DEFAULT_OUTPUT_IMAGE_ROOT = Path("/mnt/shared-storage-user/zhengyuting/SIP_exp/modified_image")
DEFAULT_CLASSIFICATION_PATH = Path("/mnt/shared-storage-user/zhengyuting/SIP_exp/classification_result.json")
DEFAULT_TEMP_ROOT = Path("/mnt/shared-storage-user/zhengyuting/SIP_exp/2_modify_image/temp_v1")
DEFAULT_CLASS_LABEL = "Chart"
PLOT2CODE_PASS_SCORE = 90
PLOT2CODE_MAX_ATTEMPTS = 3

SYSTEM_PLOT2CODE = """You are an expert Python data-visualization engineer.
Given a reference chart image, generate runnable matplotlib Python code that reproduces it.
Return only valid JSON with:
{{
  "code": "python code string only"
}}
Rules:
- Use matplotlib only (numpy allowed).
- Include figsize=({width}, {height}) exactly in your plotting code.
- Keep code executable as a standalone script.
- End with plt.savefig(output_path, dpi=150, bbox_inches='tight') where output_path is from env var OUTPUT_IMAGE.
- Do not wrap in markdown fences."""

SYSTEM_EVAL = """You are an excellent judge at evaluating visualization chart plots. The first image (reference image) is created using ground truth matplotlib code, and the second image (AI-generated image) is created using matplotlib code generated by an AI assistant. Your task is to score how well the AI-generated plot matches the ground truth plot.

### Scoring Methodology:

The AI-generated image's score is based on the following criteria, totaling a score out of 100 points:

1. Chart Types (20 points): Does the AI-generated image include all chart types present in the reference image (e.g., line charts, bar charts, etc.)?

2. Layout (10 points): Does the arrangement of subplots in the AI-generated image match the reference image (e.g., number of rows and columns)?

3. Text Content (20 points): Does the AI-generated image include all text from the reference image (e.g., titles, annotations, axis labels), excluding axis tick labels?

4. Data (20 points): How accurately do the data trends in the AI-generated image resemble those in the original image and is the number of data groups the same as in the reference image?

5. Style (20 points): Does the AI-generated image match the original in terms of colors (line colors, fill colors, etc.), marker types (point shapes, line styles, etc.), legends, grids, and other stylistic details?

6. Clarity (10 points): Is the AI-generated image clear and free of overlapping elements?

### Evaluation:

Compare the two images head to head and provide a detailed assessment.
Output MUST follow this exact plain-text template (no JSON, no markdown code block):

Comments:
- Chart Types: <comment>; subscore: <0-20>
- Layout: <comment>; subscore: <0-10>
- Text Content: <comment>; subscore: <0-20>
- Data: <comment>; subscore: <0-20>
- Style: <comment>; subscore: <0-20>
- Clarity: <comment>; subscore: <0-10>
Score: <integer>/100

Critical formatting rule:
- The final line MUST be exactly in the form: Score: N/100
- N must be an integer between 0 and 100.
Please strictly follow this format."""

SYSTEM_EDIT = """You are a matplotlib refactoring assistant.
Given current plotting code, propose limited edits (if applicable) for:
1) color changes for lines/fills, with visibly large color contrast from original choices
2) marker/line style changes
3) legend position changes
4) grid pattern/style changes
5) paraphrase text labels (title/annotations/axis labels) while keeping scientific meaning
6) reorder tabular/listed data sequence (when table-like or sequence data exists), while keeping data values unchanged

Return JSON only:
{
  "return_checklist": [
    {"aspect":"...", "old":"exact original code snippet", "new":"replacement snippet"},
    ...
  ],
  "reason": "short note"
}
Rules:
- Each old snippet must be an exact contiguous substring from the input code.
- Keep edits minimal and syntactically valid.
- If no valid edits, return empty list."""


def _image_to_data_url(path: Path) -> str:
    b = path.read_bytes()
    ext = path.suffix.lower().lstrip(".") or "png"
    return f"data:image/{ext};base64," + base64.b64encode(b).decode("utf-8")


def _extract_json_object(text: str) -> dict:
    text = (text or "").strip()
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        start = text.find("{")
        end = text.rfind("}")
        if start == -1 or end == -1 or end <= start:
            raise ValueError(f"Model output is not valid JSON: {text!r}") from None
        return json.loads(text[start : end + 1])


def _extract_python_code(text: str) -> str:
    text = (text or "").strip()
    m = re.search(r"```(?:python)?\s*(.*?)```", text, flags=re.DOTALL | re.IGNORECASE)
    if m:
        return m.group(1).strip()
    return text


def _build_client() -> OpenAI:
    return OpenAI(api_key=DEFAULT_API_KEY, base_url=DEFAULT_BASE_URL)


def _calc_figsize_ints(image_path: Path) -> Tuple[int, int]:
    with Image.open(image_path) as im:
        w_px, h_px = im.size
    # Convert to rough inch-like integers at ~100 px/inch.
    w = max(1, int(round(w_px / 100)))
    h = max(1, int(round(h_px / 100)))
    return w, h


def generate_plot_code(client: OpenAI, image_path: Path, query: str, target: str, model: str) -> str:
    width, height = _calc_figsize_ints(image_path)
    system = SYSTEM_PLOT2CODE.format(width=width, height=height)
    user_text = (
        f"Question context:\n{query}\n\n"
        f"Gold answer:\n{target}\n\n"
        "Generate chart code for the provided image."
    )
    img_url = _image_to_data_url(image_path)
    resp = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": system},
            {
                "role": "user",
                "content": [
                    {"type": "text", "text": user_text},
                    {"type": "image_url", "image_url": {"url": img_url}},
                ],
            },
        ],
        temperature=TEMPERATURE,
        max_tokens=MAX_TOKENS,
        timeout=TIMEOUT,
    )
    raw = (resp.choices[0].message.content or "").strip()
    obj = _extract_json_object(raw)
    code = _extract_python_code(str(obj.get("code", "") or ""))
    if not code:
        raise ValueError("Model returned empty plotting code.")
    return code


def render_code_to_image(code: str, output_image: Path, script_root: Path | None = None) -> Tuple[bool, str]:
    output_image.parent.mkdir(parents=True, exist_ok=True)
    if script_root is None:
        script_path = output_image.parent / "render_script.py"
    else:
        script_root.mkdir(parents=True, exist_ok=True)
        uniq = hashlib.md5(str(output_image).encode("utf-8")).hexdigest()[:12]
        script_path = script_root / f"render_script_{output_image.stem}_{uniq}.py"
    wrapped = (
        "import os\n"
        "import matplotlib\n"
        "matplotlib.use('Agg')\n"
        "import matplotlib.pyplot as plt\n\n"
        f"{code}\n\n"
        "output_path = os.environ.get('OUTPUT_IMAGE')\n"
        "if output_path:\n"
        "    try:\n"
        "        plt.savefig(output_path, dpi=150, bbox_inches='tight')\n"
        "    except Exception:\n"
        "        pass\n"
    )
    script_path.write_text(wrapped, encoding="utf-8")
    proc = subprocess.run(
        [sys.executable, str(script_path)],
        env={**os.environ, "OUTPUT_IMAGE": str(output_image)},
        capture_output=True,
        text=True,
        timeout=60,
    )
    ok = proc.returncode == 0 and output_image.exists()
    log = (proc.stdout or "") + "\n" + (proc.stderr or "")
    return ok, log.strip()


def evaluate_images(client: OpenAI, reference_image: Path, generated_image: Path, model: str) -> Dict[str, Any]:
    r_url = _image_to_data_url(reference_image)
    g_url = _image_to_data_url(generated_image)
    resp = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": SYSTEM_EVAL},
            {
                "role": "user",
                "content": [
                    {"type": "text", "text": "First image is reference, second is generated."},
                    {"type": "image_url", "image_url": {"url": r_url}},
                    {"type": "image_url", "image_url": {"url": g_url}},
                ],
            },
        ],
        temperature=TEMPERATURE,
        max_tokens=MAX_TOKENS,
        timeout=TIMEOUT,
    )
    raw = (resp.choices[0].message.content or "").strip()
    score_match = re.search(
        r"(?:^|\n)\s*Score\s*[:：-]\s*(\d{1,3})\s*(?:/\s*100|out\s+of\s+100)?\s*$",
        raw,
        flags=re.IGNORECASE | re.MULTILINE,
    )
    score = int(score_match.group(1)) if score_match else None
    if isinstance(score, int):
        score = max(0, min(100, score))
    return {
        "score": score,
        "raw_evaluation": raw,
    }


def propose_code_edits(client: OpenAI, code: str, model: str) -> Dict[str, Any]:
    resp = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": SYSTEM_EDIT},
            {"role": "user", "content": f"Current code:\n{code}"},
        ],
        temperature=TEMPERATURE,
        max_tokens=MAX_TOKENS,
        timeout=TIMEOUT,
    )
    raw = (resp.choices[0].message.content or "").strip()
    obj = _extract_json_object(raw)
    items = obj.get("return_checklist") or []
    if not isinstance(items, list):
        items = []
    cleaned: List[Dict[str, str]] = []
    for row in items:
        if not isinstance(row, dict):
            continue
        old = str(row.get("old", "") or "")
        new = str(row.get("new", "") or "")
        aspect = str(row.get("aspect", "") or "")
        if old and new:
            cleaned.append({"aspect": aspect, "old": old, "new": new})
    return {"return_checklist": cleaned, "reason": str(obj.get("reason", "") or "")}


def apply_replacements(code: str, return_checklist: List[Dict[str, str]]) -> Tuple[str, List[Dict[str, Any]]]:
    out = code
    applied: List[Dict[str, Any]] = []
    for item in return_checklist:
        old = item["old"]
        new = item["new"]
        aspect = item.get("aspect", "")
        if old in out:
            out = out.replace(old, new, 1)
            applied.append({"aspect": aspect, "old": old, "new": new, "applied": True})
        else:
            applied.append({"aspect": aspect, "old": old, "new": new, "applied": False})
    return out, applied


def run_pipeline(
    image_path: Path,
    query: str,
    target: str,
    *,
    model: str = DEFAULT_MODEL,
    workdir: Path | None = None,
) -> Dict[str, Any]:
    client = _build_client()
    root = workdir if workdir is not None else Path.cwd()
    temp_dir = root / "temp_image"
    mod_dir = root / "modified_image"
    temp_dir.mkdir(parents=True, exist_ok=True)
    mod_dir.mkdir(parents=True, exist_ok=True)

    generated_image = temp_dir / f"{image_path.stem}_generated.png"
    modified_image = mod_dir / f"{image_path.stem}_modified.png"

    code = generate_plot_code(client, image_path, query, target, model=model)
    render_ok, render_log = render_code_to_image(code, generated_image)
    if not render_ok:
        return {
            "ok": False,
            "error": "Initial render failed",
            "render_log": render_log,
            "generated_code": code,
        }

    eval_result = evaluate_images(client, image_path, generated_image, model=model)
    edit_plan = propose_code_edits(client, code, model=model)
    modified_code, apply_log = apply_replacements(code, edit_plan["return_checklist"])
    mod_ok, mod_log = render_code_to_image(modified_code, modified_image)

    return {
        "ok": True,
        "query": query,
        "target": target,
        "image_path": str(image_path),
        "generated_code": code,
        "generated_image": str(generated_image),
        "evaluation": eval_result,
        "return_checklist": edit_plan["return_checklist"],
        "edit_reason": edit_plan["reason"],
        "applied_replacements": apply_log,
        "modified_code": modified_code,
        "modified_image": str(modified_image) if mod_ok else "",
        "modified_render_ok": mod_ok,
        "modified_render_log": mod_log,
    }


def run_pipeline_with_paths(
    *,
    image_path: Path,
    query: str,
    target: str,
    generated_image: Path,
    modified_image: Path,
    temp_root: Path | None = None,
    model: str = DEFAULT_MODEL,
) -> Dict[str, Any]:
    client = _build_client()
    script_root = (temp_root / "render_scripts") if temp_root is not None else None
    plot2code_score = None
    best_render_log = ""
    plot2code_success = False
    retry_times = 0
    final_code = ""
    final_generated_image = generated_image

    for attempt in range(1, PLOT2CODE_MAX_ATTEMPTS + 1):
        retry_times = attempt - 1
        attempt_image = generated_image.with_name(f"{generated_image.stem}_try{attempt}{generated_image.suffix}")
        code = generate_plot_code(client, image_path, query, target, model=model)
        render_ok, render_log = render_code_to_image(code, attempt_image, script_root=script_root)
        final_code = code
        final_generated_image = attempt_image
        best_render_log = render_log
        if not render_ok:
            continue

        eval_result = evaluate_images(client, image_path, attempt_image, model=model)
        score = eval_result.get("score")
        plot2code_score = int(score) if isinstance(score, int) else None
        if isinstance(plot2code_score, int) and plot2code_score >= PLOT2CODE_PASS_SCORE:
            plot2code_success = True
            break

    if not plot2code_success:
        return {
            "ok": False,
            "error": "plot2code failed to reach score threshold after retries",
            "render_log": best_render_log,
            "plot2code_score": plot2code_score,
            "plot2code_success": False,
            "plot2code_retry_times": retry_times,
            "generated_code": final_code,
            "generated_image": str(final_generated_image),
            "modified_image": str(modified_image),
            "modified_code": "",
            "return_checklist": [],
            "applied_replacements": [],
            "modified_render_ok": False,
        }

    edit_plan = propose_code_edits(client, final_code, model=model)
    modified_code, apply_log = apply_replacements(final_code, edit_plan["return_checklist"])
    mod_ok, mod_log = render_code_to_image(modified_code, modified_image, script_root=script_root)
    return {
        "ok": True,
        "query": query,
        "target": target,
        "image_path": str(image_path),
        "plot2code_score": plot2code_score,
        "plot2code_success": True,
        "plot2code_retry_times": retry_times,
        "generated_code": final_code,
        "generated_image": str(final_generated_image),
        "return_checklist": edit_plan["return_checklist"],
        "edit_reason": edit_plan["reason"],
        "applied_replacements": apply_log,
        "modified_code": modified_code,
        "modified_image": str(modified_image) if mod_ok else "",
        "modified_render_ok": mod_ok,
        "render_log": mod_log,
    }


def _load_classification_map(path: Path) -> Dict[str, str]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"Classification file must be a JSON object: {path}")
    out: Dict[str, str] = {}
    for k, v in data.items():
        out[str(k)] = str(v)
    return out


def _iter_qa_files(root: Path) -> List[Path]:
    files = sorted(root.rglob("*_qa.json"))
    if not files:
        raise FileNotFoundError(f"No '*_qa.json' files found under {root}")
    return files


def _resolve_image_path(image_root: Path, image_rel: str) -> Path:
    rel = image_rel.strip().replace("\\", "/")
    candidate_a = image_root / rel
    if candidate_a.exists():
        return candidate_a
    if rel.startswith("image/"):
        candidate_b = image_root / rel[len("image/") :]
        if candidate_b.exists():
            return candidate_b
    return candidate_a


def _build_output_paths(
    image_rel: str,
    *,
    output_root: Path,
    temp_root: Path,
) -> Tuple[Path, Path]:
    rel = Path(image_rel.replace("\\", "/"))
    rel_for_output = rel
    if rel_for_output.parts and rel_for_output.parts[0] == "image":
        rel_for_output = Path(*rel_for_output.parts[1:])
    rel_no_ext = rel.with_suffix("")
    rel_no_ext_output = rel_for_output.with_suffix("")
    generated = temp_root / "temp_image" / rel_no_ext.parent / f"{rel_no_ext.name}_generated.png"
    modified = output_root / rel_no_ext_output.parent / f"{rel_no_ext_output.name}.png"
    return generated, modified


def run_batch(
    *,
    qa_root: Path,
    image_root: Path,
    output_image_root: Path,
    classification_path: Path,
    temp_root: Path,
    class_label: str,
    model: str,
    max_workers: int,
) -> Dict[str, Any]:
    class_label_norm = class_label.strip().lower()
    qa_files = _iter_qa_files(qa_root)
    cls_map = _load_classification_map(classification_path)
    temp_root.mkdir(parents=True, exist_ok=True)
    output_image_root.mkdir(parents=True, exist_ok=True)

    results: List[Dict[str, Any]] = []
    qa_file_results_map: Dict[str, List[Dict[str, Any]]] = {}
    counters = {
        "total_items": 0,
        "class_matched": 0,
        "processed": 0,
        "skipped_class": 0,
        "skipped_missing_image": 0,
        "failed": 0,
    }

    task_specs: List[Dict[str, Any]] = []
    for qa_file in qa_files:
        payload = json.loads(qa_file.read_text(encoding="utf-8"))
        if not isinstance(payload, list):
            continue
        qa_key = str(qa_file)
        qa_file_results_map.setdefault(qa_key, [])
        for row in payload:
            counters["total_items"] += 1
            if not isinstance(row, dict):
                continue
            image_paths = row.get("image_path")
            if isinstance(image_paths, list) and image_paths:
                image_rel = str(image_paths[0])
            else:
                image_rel = str(image_paths or "")
            image_rel = image_rel.strip()
            if not image_rel:
                continue

            image_class = cls_map.get(image_rel, "")
            if image_class.strip().lower() != class_label_norm:
                counters["skipped_class"] += 1
                continue
            counters["class_matched"] += 1

            source_image = _resolve_image_path(image_root, image_rel)
            if not source_image.exists():
                counters["skipped_missing_image"] += 1
                result = {
                    "qa_file": qa_key,
                    "id": str(row.get("id", "")),
                    "image_path": image_rel,
                    "plot2code_score": None,
                    "plot2code_success": False,
                    "plot2code_retry_times": 0,
                    "generated_image": "",
                    "generated_code": "",
                    "modified_code": "",
                    "return_checklist": [],
                    "applied_replacements": [],
                    "modified_render_ok": False,
                    "error": "Source image not found",
                    "render_log": f"resolved_image_path={source_image}",
                }
                qa_file_results_map[qa_key].append(result)
                results.append(result)
                continue

            generated_image, modified_image = _build_output_paths(
                image_rel,
                output_root=output_image_root,
                temp_root=temp_root,
            )
            task_specs.append(
                {
                    "qa_file": qa_key,
                    "id": str(row.get("id", "")),
                    "image_path": image_rel,
                    "image_class": image_class,
                    "query": str(row.get("query", "")),
                    "target": str(row.get("target", "")),
                    "source_image": source_image,
                    "generated_image": generated_image,
                    "modified_image": modified_image,
                }
            )

    if task_specs:
        pool_size = max(1, int(max_workers))
        with concurrent.futures.ThreadPoolExecutor(max_workers=pool_size) as executor:
            future_map: Dict[concurrent.futures.Future, Dict[str, Any]] = {}
            for spec in task_specs:
                future = executor.submit(
                    run_pipeline_with_paths,
                    image_path=spec["source_image"],
                    query=spec["query"],
                    target=spec["target"],
                    generated_image=spec["generated_image"],
                    modified_image=spec["modified_image"],
                    temp_root=temp_root,
                    model=model,
                )
                future_map[future] = spec

            for future in concurrent.futures.as_completed(future_map):
                spec = future_map[future]
                try:
                    result = future.result()
                except Exception as exc:
                    result = {
                        "ok": False,
                        "plot2code_score": None,
                        "plot2code_success": False,
                        "plot2code_retry_times": 0,
                        "generated_image": str(spec["generated_image"]),
                        "generated_code": "",
                        "modified_code": "",
                        "return_checklist": [],
                        "applied_replacements": [],
                        "modified_render_ok": False,
                        "error": "Unhandled worker exception",
                        "render_log": str(exc),
                    }

                result.update(
                    {
                        "qa_file": spec["qa_file"],
                        "id": spec["id"],
                        "image_path": spec["image_path"],
                        "image_class": spec["image_class"],
                    }
                )
                if not result.get("ok", False):
                    counters["failed"] += 1
                else:
                    counters["processed"] += 1

                normalized_result = {
                    "id": result.get("id", ""),
                    "image_path": result.get("image_path", ""),
                    "plot2code_score": result.get("plot2code_score"),
                    "plot2code_success": result.get("plot2code_success", False),
                    "plot2code_retry_times": result.get("plot2code_retry_times", 0),
                    "generated_image": result.get("generated_image", ""),
                    "generated_code": result.get("generated_code", ""),
                    "modified_code": result.get("modified_code", ""),
                    "return_checklist": result.get("return_checklist", []),
                    "applied_replacements": result.get("applied_replacements", []),
                    "modified_render_ok": result.get("modified_render_ok", False),
                    "error": result.get("error", ""),
                    "render_log": result.get("render_log", ""),
                }
                qa_file_results_map[spec["qa_file"]].append(normalized_result)
                results.append(normalized_result)
                print(
                    f"[{counters['processed'] + counters['failed']}] {spec['image_path']} -> "
                    f"{result.get('modified_image', '') or 'FAILED'}",
                    flush=True,
                )

    for qa_file in qa_files:
        qa_key = str(qa_file)
        qa_out_name = qa_file.stem.replace("_qa", "") + "_v1_process.json"
        qa_out_path = temp_root / qa_out_name
        qa_out_payload = {
            "qa_file": qa_key,
            "class_label": class_label,
            "plot2code_pass_score": PLOT2CODE_PASS_SCORE,
            "plot2code_max_attempts": PLOT2CODE_MAX_ATTEMPTS,
            "results": qa_file_results_map.get(qa_key, []),
        }
        qa_out_path.write_text(json.dumps(qa_out_payload, ensure_ascii=False, indent=2), encoding="utf-8")

    summary = {
        "mode": "batch",
        "qa_root": str(qa_root),
        "image_root": str(image_root),
        "output_image_root": str(output_image_root),
        "classification_path": str(classification_path),
        "temp_root": str(temp_root),
        "class_label": class_label,
        "model": model,
        "plot2code_pass_score": PLOT2CODE_PASS_SCORE,
        "plot2code_max_attempts": PLOT2CODE_MAX_ATTEMPTS,
        "stats": counters,
        "results": results,
    }
    summary_path = temp_root / "batch_summary.json"
    summary_path.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
    summary["summary_path"] = str(summary_path)
    return summary


def main() -> None:
    parser = argparse.ArgumentParser(description="Single test framework: chart2code -> evaluate -> controlled edits")
    parser.add_argument("--batch", action="store_true", help="Run batch mode on all *_qa.json files.")
    parser.add_argument("--qa-root", type=Path, default=DEFAULT_QA_ROOT, help="Input QA root directory.")
    parser.add_argument("--image-root", type=Path, default=DEFAULT_IMAGE_ROOT, help="Input image root directory.")
    parser.add_argument(
        "--output-image-root",
        type=Path,
        default=DEFAULT_OUTPUT_IMAGE_ROOT,
        help="Output image root directory.",
    )
    parser.add_argument(
        "--classification-path",
        type=Path,
        default=DEFAULT_CLASSIFICATION_PATH,
        help="Image classification mapping JSON path.",
    )
    parser.add_argument("--temp-root", type=Path, default=DEFAULT_TEMP_ROOT, help="Intermediate output directory.")
    parser.add_argument("--class-label", type=str, default=DEFAULT_CLASS_LABEL, help="Only process this class label.")
    parser.add_argument("--image", type=Path, default=Path(DEFAULT_IMAGE_PATH), help="Reference chart image path")
    parser.add_argument("--query", type=str, default=QUERY)
    parser.add_argument("--target", type=str, default=TARGET)
    parser.add_argument("--model", type=str, default=DEFAULT_MODEL)
    parser.add_argument("--max-workers", type=int, default=8, help="Thread pool size for batch mode.")
    parser.add_argument("--output", "-o", type=Path, default=None, help="Write full JSON result")
    args = parser.parse_args()

    if args.batch:
        result = run_batch(
            qa_root=args.qa_root,
            image_root=args.image_root,
            output_image_root=args.output_image_root,
            classification_path=args.classification_path,
            temp_root=args.temp_root,
            class_label=args.class_label,
            model=args.model,
            max_workers=args.max_workers,
        )
        print(json.dumps(result["stats"], ensure_ascii=False, indent=2))
        print(f"\nWrote summary to {result['summary_path']}")
        if args.output is not None:
            args.output.parent.mkdir(parents=True, exist_ok=True)
            args.output.write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")
            print(f"Wrote full batch result to {args.output}")
        return

    result = run_pipeline(args.image, args.query, args.target, model=args.model, workdir=Path.cwd())
    print(json.dumps(result, ensure_ascii=False, indent=2))
    if args.output is not None:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")
        print(f"\nWrote to {args.output}")


if __name__ == "__main__":
    main()